Staff Required Error
zollf/CITS3200 pull request #113
Opened 2021-10-02 11:17 UTC by jaydenteo

Fixes #83 

## Proposed Changes
  - Created staff_required.html (copying admin.html) to route to. 
  - Not sure if an error or relevant should appear? Currently just goes to a blank admin page. 
  -

2021-10-02 12:42 UTC, zollf requested changes
So i just realized i never committed this file :( 

It should be similar to https://github.com/zollf/CITS3200/blob/main/app/resources/templates/login.html without the login fields. Instead, it's just text with `Please login into a staff account` with a logout button.

2021-10-09 10:44 UTC, APM246 commented
The user flow of staff required isn't right. If an admin goes straight to /admin without logging in, gets redirected to the login page and then logs in, they'll be brought to the staff required page instead of the admin page

2021-10-09 10:48 UTC, APM246 requested changes

2021-10-09 10:48 UTC, APM246 commented on app/resources/templates/staff_required.html
> +      <form method="POST" class="logout-form">
this message does not need to be within a form element

2021-10-09 12:51 UTC, APM246 approved these changes

2021-10-09 12:52 UTC, APM246 approved these changes

2021-10-09 12:52 UTC, APM246 approved these changes

2021-10-09 13:59 UTC, zollf approved these changes

2021-10-09 14:01 UTC, merged