Allow Bay Description to be Blank
zollf/CITS3200 pull request #114
Opened 2021-10-02 12:00 UTC by jaydenteo

Fixes #111 

## Proposed Changes
  - Can add a space character to description successfully now. 
  - Resolves - "Also, if a space is inputted into description, it redirects to a json error page."
  - Could not figure out how to get past input validation ("Please fill in this field")!

2021-10-02 12:36 UTC, zollf commented
so i've made everything required by default with our custom form tag:
> https://github.com/zollf/CITS3200/blob/main/app/admin/templatetags/admin.py
> Specifically: `<input type="text" id="{{field.name}}" name="{{field.name}}" value="{{data|key:field.name}}" required {% if static %}disabled{% endif %}/>`
> https://github.com/zollf/CITS3200/blob/main/app/resources/templates/form.html 

So it's just HTML and embedded validation. A possible solution is to add another parameter for required, or some way to pass whether a field is required or not. I would NOT recommend extending `fields` param to handle requirement e.g., 
`{% create_form 'carparks' carpark 'name:text:Username:required|desc:text:Description:required' "/admin/carpark/add" %}` as label is optional already and would make the code more unreadable.

A possible option is `{% create_form 'carparks' carpark 'name:r_text:Username|desc:r_text:Description' "/admin/carpark/add" %}` and then spliting `r_text` (and other field types) into `type` and `required` based on whether it has `r` or not.

Another option is just having another param `{% create_form 'carparks' carpark 'name:text:Username|desc:text:Description' "/admin/carpark/add" required=name|desc %}`. Tho you'll have to change all existing ones as they could error without param, whereas the other wont have that issue but would make everything not required.

Any better solutions are welcomed

2021-10-09 17:42 UTC, APM246 requested changes

2021-10-09 17:42 UTC, APM246 commented on app/parking/models.py
> +    description = models.TextField(blank=True)
You will need to run ``` docker-compose run django python manage.py makemigrations ``` to create the migration file that updates the database schema. That file can be committed as well.

2021-10-09 17:42 UTC, APM246 commented on app/admin/templatetags/admin.py
> +    print(fields_matrix)
This print call should be removed

2021-10-09 17:42 UTC, APM246 commented on app/admin/templatetags/admin.py
> +                'type': field_arr[1] if "r_" not in field_arr[1] else field_arr[1][2:],
Maybe a different letter than r_ should be used since it is denoting a *non*-required field. E.g. n_

2021-10-10 07:05 UTC, APM246 approved these changes

2021-10-10 07:05 UTC, merged