Email Smtp Setup
zollf/CITS3200 pull request #124
Opened 2021-10-09 07:49 UTC by zollf

Closes #75

I've added a model to keep track of email events. This is more to keep track of emails somewhere in the db, the views are just extra.

## Proposed Changes
  - Added emails page `admin/emails`
  - Added email page `admin/emails/view/<int:pk>`
  - Added API endpoint for email testing `api/emails/test`
  - Added model for keeping track of email events if needed
  - Added .env variables 
  - Added env variables to `deploy.yml`

## TODO:
- currently, I've limited emails to 10 on the page so loading everything isn't an issue (it starts to be an issue in the 1000s usually), if someone has spare time they can do pagination. However its not a big deal as its logged in db which is more important.

2021-10-09 12:37 UTC, APM246 commented
I'll try to review this tomorrow (latest by Monday)

2021-10-11 16:23 UTC, APM246 requested changes

2021-10-11 16:23 UTC, APM246 commented on app/emails/send.py
> +        payload="",
Shouldn't this be payload = html_body?

2021-10-11 16:23 UTC, APM246 commented on app/emails/send.py
> +from django.core.mail import send_mail, EmailMultiAlternatives
remove unused import send_email

2021-10-11 16:26 UTC, zollf commented on app/emails/send.py
> +        payload="",
its supposed to be data actually, i need to change that

2021-10-12 05:57 UTC, APM246 approved these changes

2021-10-12 08:12 UTC, merged