Feature/timeslot buffer
zollf/CITS3200 pull request #129
Opened 2021-10-10 17:16 UTC by zollf

Closes #126 

## Proposed Changes
  - Added -/+ 30min buffers on submission (these cannot go beyond 00:00 and 24:00)

2021-10-11 15:10 UTC, APM246 requested changes

2021-10-11 15:10 UTC, APM246 commented on app/parking/views.py
> +                end_time_hr = min(end_time_hr + 1, 23)
This does not work if the end of someone's booking is to 11:30 P.M. The end_time will end up being 11:00 P.M. instead of 12 A.M.

2021-10-11 16:02 UTC, zollf commented
Honestly looking back at this. This needs more work... It just doesn't work

Ill spent some more time doing this + writing test for `/api/bookings` endpoint

2021-10-16 12:56 UTC, zollf commented
declined

2021-10-16 12:56 UTC, closed without merging