Work In Progress: Feature/authentication
zollf/CITS3200 pull request #34
Opened 2021-08-31 09:19 UTC by APM246

Having issues with creating a superuser to test out login page. The error is "create_superuser() missing 1 required positional argument: phone". The issue would be fixed if migrations were applied correctly but it doesn't seem to recognise my changes to create_superuser().

#22

2021-08-31 10:48 UTC, zollf requested changes

2021-08-31 10:48 UTC, zollf commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
why are these removed? This is a key, value table. These key-values are only every used once and there is no need to make them create-able from the admin panel

2021-08-31 10:48 UTC, zollf commented on app/resources/templates/registration/login.html
> +{% extends "../base.html" %}
this file should be in templates, no need to segment templates into folders. 
This would also make this `{% extends 'base.html' %} `

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +        user = self.model(email=email, phone=phone **extra_fields)
`user = self.model(email=email, phone=phone,  **extra_fields)` u forgot the comma

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +    hub_id = models.IntegerField()
leave this out for now

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +    locked = models.BooleanField()
`default=False`

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +    last_login = models.DateTimeField()
`null=True`

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +    login_count = models.IntegerField()
`default=0`

2021-08-31 10:48 UTC, zollf commented on app/core/settings.py
> +LOGIN_REDIRECT_URL = 'admin/settings'
`admin/`

2021-08-31 10:48 UTC, zollf commented on app/resources/templates/registration/login.html
> +        {{ form.username }}
please use `<input type="text" name="username" id="username"/>` just for consistence sake, and same with the label

2021-08-31 10:48 UTC, zollf commented on app/authentication/models.py
> +        if extra_fields.get('is_staff') is not True:
i dont think u need these checks, as youre setting them to True immediately before

2021-08-31 10:50 UTC, zollf commented
You can delete you db my running `docker-compose rm - v mysql` then you'll need to initialize again `docker-compose up mysql` then rerun the migrations. 

You can delete your migration file and redo them as we haven't committed them into `main` if you need to.

2021-09-01 13:12 UTC, APM246 commented on app/authentication/models.py
> +    hub_id = models.IntegerField()
Do u mean leave out hub_id?

2021-09-01 13:14 UTC, zollf commented on app/authentication/models.py
> +    hub_id = models.IntegerField()
yea leave out hub_id, github just highlights chunk of code when i comment on a line. By the bottom line is the one i mean so hub_id

2021-09-01 13:19 UTC, APM246 commented on app/resources/templates/registration/login.html
> +        {{ form.username }}
Doesn't this take advantage of Django's Form objects which improves syntax clarity/simplicity

2021-09-01 13:35 UTC, APM246 commented
> You can delete you db my running `docker-compose rm - v mysql` then you'll need to initialize again `docker-compose up mysql` then rerun the migrations. 
> You can delete your migration file and redo them as we haven't committed them into `main` if you need to.

Getting this error after deleting SQL image + migrations and re-running migrations from scratch: 
django.db.utils.OperationalError: (1050, "Table 'django_admin_log' already exists")

Trying to investigate

2021-09-01 13:35 UTC, zollf commented on app/resources/templates/registration/login.html
> +        {{ form.username }}
since youre using LoginView and its doing it all for you. Its fine

2021-09-01 13:39 UTC, zollf commented
maybe try deleting again. I dont see why deleting the mysql volume wouldn't remove that specific table. Removing the volume removes the whole db. The only way i can see this happening is if you arent deleting the correct database. https://gyazo.com/db8083fc1876e11ef6c36102f0371319

2021-09-01 13:41 UTC, zollf commented
i just noticed i didnt type the command correct *facepalm* its `docker-compose rm -v mysql` no space between - and v

2021-09-01 13:41 UTC, APM246 commented
Nvm ended up fixing it, ran some commands in the wrong order. Will try to commit new changes soon.

2021-09-01 13:56 UTC, APM246 commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
Hmm for some reason this code got removed when I ran migrations from scratch

2021-09-01 13:58 UTC, APM246 commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
Oh nvm was that code in a later commit? Cause I haven't merged from main recently

2021-09-01 13:59 UTC, zollf commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
`git checkout origin/main app/admin_settings/migrations/0001_initial.py`

2021-09-01 14:11 UTC, APM246 commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
I believe insertData should have "self" as the first arg since it's a method

2021-09-01 14:12 UTC, zollf commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
isnt it a static method?

anyway i dont know if it matters, it works for you right?

2021-09-01 14:16 UTC, APM246 commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
Oh right yea. In that case I've added @staticmethod to getKeys() and getDict() (to get rid of the VS Code squiggy line)

2021-09-01 14:19 UTC, zollf commented on app/admin_settings/migrations/0001_initial.py
> -    def insertData(apps, schema_editor):
Thanks. What plugin is that, ill install it

2021-09-01 14:37 UTC, APM246 commented
Authentication now works but I'm not ready to merge (still have a few things to tweak)

2021-09-01 14:39 UTC, zollf commented
Thanks. Ill add user page in the backend so we can hook it up easily straight after this gets merged. You also have conflicts btw.

2021-09-01 14:40 UTC, APM246 commented
Yep that's one of the things I wanted to tweak, merging main atm

2021-09-01 14:47 UTC, APM246 commented
The Django test needs to be modified because I've now added login_required and staff_member_required decorators to the admin view

2021-09-01 14:47 UTC, zollf commented
ill do it now

2021-09-01 14:47 UTC, APM246 commented
Could I try doing it?

2021-09-01 14:48 UTC, zollf commented
yea go for it

2021-09-01 14:49 UTC, zollf requested changes

2021-09-01 14:49 UTC, zollf commented on app/resources/templates/base.html
> +<<<<<<< HEAD
conflict lines

2021-09-01 14:57 UTC, APM246 commented on app/resources/templates/base.html
> +<<<<<<< HEAD
Jeez I'm really out of it, I can't even get a merge right

2021-09-02 00:49 UTC, zollf approved these changes
Good work

2021-09-02 00:50 UTC, merged