Feature/carpark admin panel
zollf/CITS3200 pull request #55
Opened 2021-09-04 05:53 UTC by zollf

Kinda went overboard lol

I added a custom tag to django templates that will build the tables and forms for us. 

closes #44

2021-09-13 18:54 UTC, APM246 requested changes

2021-09-13 18:54 UTC, APM246 commented on app/admin/templatetags/admin.py
> +    Usage: `{% create_form 'carparks' carpark 'name|description' %}`
Should this be Usage: `{% create_table ...   instead?

2021-09-13 18:54 UTC, APM246 commented on app/resources/templates/user.html
> +{% endblock %}
Should the users/view/id page have a delete button similar to carparks/view/id?

2021-09-13 19:02 UTC, APM246 commented
Perhaps the parking folder in app should be within a folder "api" for clarity

2021-09-13 20:33 UTC, APM246 commented
Just realised modifying a carpark ends up adding a new entry instead, is this a bug or because the page is still a work in progress?

2021-09-14 05:05 UTC, APM246 commented
Does the code ensure API calls can only be made by authenticated users?  
https://www.django-rest-framework.org/api-guide/views/#api-policy-decorators and 
https://www.django-rest-framework.org/api-guide/settings/ discusses how to restrict API calls.

2021-09-14 10:35 UTC, zollf commented
> 
> 
> Does the code ensure API calls can only be made by authenticated users?
> https://www.django-rest-framework.org/api-guide/views/#api-policy-decorators and
> https://www.django-rest-framework.org/api-guide/settings/ discusses how to restrict API calls.

so we can actually just do `@login_required(login_url="/login")` which will send unauthorized people to login https://gyazo.com/979fb41e6083803584036be5e938c3b4. I'll probably just do that for know, as he hasn't spent much on security .

2021-09-14 10:36 UTC, zollf commented
> 
> 
> Just realised modifying a carpark ends up adding a new entry instead, is this a bug or because the page is still a work in progress?

🙇

2021-09-14 10:39 UTC, zollf commented
> 
> 
> Perhaps the parking folder in app should be within a folder "api" for clarity

we should probably leave this as everyone will then have to do the migrations, which is a hassle. We'll add the newer stuff to the folder api, and bays will just sit in parking.

2021-09-14 10:42 UTC, zollf commented on app/resources/templates/user.html
> +{% endblock %}
yea itll have the same buttons, there are other buttons that we will add later, or can just find a way to optionally add them in.

2021-09-16 09:55 UTC, APM246 reviewed
Modifying a car park still ends up adding a new car park rather than modifying the current details.

2021-09-16 10:03 UTC, APM246 approved these changes
Looks good

2021-09-16 10:03 UTC, merged