Feature/bay booking card
zollf/CITS3200 pull request #57
Opened 2021-09-10 17:27 UTC by APM246

![Capture](https://user-images.githubusercontent.com/50038558/132893586-3265c74f-92c5-4ee4-bbf4-c05ee9a8c6dc.PNG)
![2](https://user-images.githubusercontent.com/50038558/132893593-540208b6-f887-414b-8ba6-c2661c1e632d.PNG)
![3](https://user-images.githubusercontent.com/50038558/132893600-fdb8c9b3-2265-4294-bb0e-9c665b440e9c.PNG)

Could use some CSS improvements but the functionality is there

Closes #43

2021-09-11 09:11 UTC, zollf requested changes
Looking really good!

2021-09-11 09:11 UTC, zollf commented on frontend/components/BookingForm/steps/Details/BayBookings/index.tsx
> +import timePeriods from '../../../../../lib/Times';
`import timePeriods from '@/frontend/lib/Times';`

ive set up an alias so that we don't need to do a whole bunch of backs.

https://github.com/zollf/CITS3200/blob/73bb32a330d960798f10302ce1905a7a7a512a4d/webpack.config.js#L57
https://github.com/zollf/CITS3200/blob/73bb32a330d960798f10302ce1905a7a7a512a4d/tsconfig.json#L30

2021-09-11 09:12 UTC, zollf requested changes

2021-09-11 09:12 UTC, zollf commented on frontend/components/BookingForm/steps/Details/BayBookings/index.tsx
> +  const listItems = cleanedTimes.map((bookedTime) => {
alot of this can be wrapped in a `useMemo` to avoid unnecessary recalculation on state changes. In this case typing in the inputs will cause state changes, which rerenders the Details Step component, including its children, therefore re-calcating all this functionality. To avoid this we memoize the result of listItems and only rerender when the its dependency of bayTimes changes. 

Ideally you would do
```tsx
const items = useMemo(() => {
  // timeSlugs
  // timeSlugs Sort
  // clean times
  return // cleanTimes map
}, [bayTimes]); 
```

2021-09-11 19:48 UTC, APM246 commented
Added the feedback, should be good to merge

2021-09-12 02:59 UTC, zollf approved these changes
Good work

2021-09-12 04:40 UTC, merged