Feature/admin panel users
zollf/CITS3200 pull request #60
Opened 2021-09-16 17:22 UTC by APM246

Completed API endpoints for User model. Users can be added, modified or deleted including changing their password (through Django's default PBKDF2 hashing algorithm).

Closes #58

2021-09-17 03:24 UTC, zollf requested changes
You'll need to add the new fields (email, phone) to UsersEdit in `app/admin/views` `def UsersEdit(request, pk):`

2021-09-17 03:24 UTC, zollf commented on app/resources/templates/user.html
> +  {% create_form 'users' user 'username:text|password:password|email:text|phone:text' %}
we should make a new field called email in `form.html` so we can have embedded email validation by the browser. So it be `email:email` and in `form.html` it be `<input type="email" ... />

2021-09-17 03:24 UTC, zollf commented on app/resources/templates/user.html
> +  {% create_form 'users' user 'username:text|password:password|email:text|phone:text' %}
we aneed another field for is_staff which would be a checkbox. As when i login as a newly created user i cant access admin stuff. This would be one of the permission thing in this case.

2021-09-17 06:38 UTC, APM246 commented
A couple of issues remain:
- If non-admin user tries to access admin site, the site shouldn't crash and should display "not an admin" message instead
- Admin panel should gracefully handle users changing their own details such as password (redirect to login page)
- Admin panel should not let users delete their own account

2021-09-17 07:26 UTC, zollf commented
1. It doesn't crash, shows the correct error, on live site itll say page unknown if you're not staff and logged in. You can set a redirect if they aren't staff in the decorator
2. You can do this in your user api with `redirect` and other functionality. In the design, password isn't a field on the user page, i added it there to test, please remove it and add a change password button, this should be flag in the form tag to turn it on, or have a params for extra buttons or something in the template tag. Up to you.
3. If the user in viewing is the user itself, hide the delete button somehow in the template tag. Up to you. 
All of these can be done later or in here, if doing later make issues please

2021-09-17 07:27 UTC, zollf approved these changes

2021-09-17 07:32 UTC, APM246 commented
I'll work on the changes in here since they are significant and the branch shouldn't be merged until they are addressed

2021-09-17 14:50 UTC, APM246 commented
> > 1. It doesn't crash, shows the correct error, on live site itll say page unknown if you're not staff and logged in. You can set a redirect if they aren't staff in the decorator
> > 2. You can do this in your user api with `redirect` and other functionality. In the design, password isn't a field on the user page, i added it there to test, please remove it and add a change password button, this should be flag in the form tag to turn it on, or have a params for extra buttons or something in the template tag. Up to you.
> > 3. If the user in viewing is the user itself, hide the delete button somehow in the template tag. Up to you.
> >    All of these can be done later or in here, if doing later make issues please
> 
> In reference to issue, I'm trying to figure out how to

I've resolved Issues 1 and 3, working on 2 now

2021-09-18 14:59 UTC, zollf approved these changes
Good work

2021-09-18 16:38 UTC, merged