WIP Feature/settings connect
zollf/CITS3200 pull request #99
Opened 2021-09-25 13:01 UTC by APM246

#98 

## Proposed Changes
  - So far I have connected phone number and global start/end dates.
  - Currently working on help guide text areas

2021-09-25 13:01 UTC, APM246 commented
Tests will fail because integration test does not wait for phone number fetch call.

2021-09-26 05:08 UTC, zollf requested changes

2021-09-26 05:08 UTC, zollf commented on frontend/lib/BayInitialProps.ts
> +  console.log(times.length);
remove

2021-09-26 05:08 UTC, zollf commented on frontend/lib/BayInitialProps.ts
> +    console.log(GlobalStartTime);
remove

2021-09-26 05:08 UTC, zollf commented on frontend/lib/BayInitialProps.ts
> +const getGlobalTimes = async () => {
there's a much better way to do this. 
In https://github.com/zollf/CITS3200/blob/main/frontend/entrypoints/home.tsx

You can do `document.getElementById('globalStartTime').dataset.globalStartTime` and `document.getElementById('globalEndTime').dataset.globalEndTime`. As data tags in https://github.com/zollf/CITS3200/blob/main/app/resources/templates/index.html . 
So `<div id="globalStartTime" data-globalStartTime="{{ settings.globalStartTime }}" ></div>` After that you can pass them as probs to the `<BookingForm initialProps={initialProps} />`

That way we don't need to fetch this much for simple data. 
Either that or u can do a fetch for all initial props which should include car parks as well, since they will never change and only need to be request once.

2021-09-26 05:08 UTC, zollf commented on frontend/lib/BayInitialProps.ts
> +const getGlobalTimes = async () => {
After that you can just pass those variables into here as paramaters

2021-09-26 05:08 UTC, zollf commented on frontend/components/BookingForm/steps/Carpark/index.tsx
> +        Any additional enquiries, call <a href="">{phoneNumber}</a>
```tsx
<a href={`tel:${phoneNumber}`}>{phoneNumber}</a>
```

2021-09-26 17:29 UTC, APM246 commented
1 remaining thing is to modify Booking.integration test so it doesn't fail. I'm kinda struggling with that.

2021-09-27 08:48 UTC, zollf commented
i've updated you code a little bit and mended the tests

2021-09-27 08:48 UTC, zollf approved these changes

2021-09-27 09:51 UTC, APM246 commented
Thanks

2021-09-27 09:52 UTC, merged